# .gitlab-ci.yml
# GitLab CI/CD pipeline for publishing packages

variables:
  REPO_URL: ${PACKAGE_REPO_URL}  # Set in GitLab CI/CD variables

stages:
  - build
  - publish

# DEB Package Pipeline
build-deb:
  stage: build
  image: debian:bookworm
  script:
    - apt-get update && apt-get install -y dpkg-dev debhelper
    - dpkg-deb --build ./package mypackage_${CI_COMMIT_TAG}_amd64.deb
  artifacts:
    paths:
      - "*.deb"
    expire_in: 1 hour
  rules:
    - if: $CI_COMMIT_TAG

publish-deb:
  stage: publish
  image: curlimages/curl:latest
  needs: [build-deb]
  script:
    - |
      curl -X POST \
        -H "X-API-Key: ${PACKAGE_REPO_API_KEY}" \
        -F "file=@mypackage_${CI_COMMIT_TAG}_amd64.deb" \
        "${REPO_URL}/api/v1/upload/deb"
  rules:
    - if: $CI_COMMIT_TAG

# RPM Package Pipeline
build-rpm:
  stage: build
  image: fedora:latest
  script:
    - dnf install -y rpm-build rpmdevtools
    - rpmdev-setuptree
    - rpmbuild -ba mypackage.spec
    - cp ~/rpmbuild/RPMS/x86_64/*.rpm .
  artifacts:
    paths:
      - "*.rpm"
    expire_in: 1 hour
  rules:
    - if: $CI_COMMIT_TAG

publish-rpm:
  stage: publish
  image: curlimages/curl:latest
  needs: [build-rpm]
  script:
    - |
      for rpm in *.rpm; do
        curl -X POST \
          -H "X-API-Key: ${PACKAGE_REPO_API_KEY}" \
          -F "file=@${rpm}" \
          "${REPO_URL}/api/v1/upload/rpm"
      done
  rules:
    - if: $CI_COMMIT_TAG

# Arch Linux Package Pipeline
build-arch:
  stage: build
  image: archlinux:latest
  script:
    - pacman -Sy --noconfirm base-devel
    - useradd -m builder && chown -R builder:builder .
    - su builder -c "makepkg -s --noconfirm"
  artifacts:
    paths:
      - "*.pkg.tar.zst"
    expire_in: 1 hour
  rules:
    - if: $CI_COMMIT_TAG

publish-arch:
  stage: publish
  image: curlimages/curl:latest
  needs: [build-arch]
  script:
    - |
      curl -X POST \
        -H "X-API-Key: ${PACKAGE_REPO_API_KEY}" \
        -F "file=@*.pkg.tar.zst" \
        "${REPO_URL}/api/v1/upload/arch"
  rules:
    - if: $CI_COMMIT_TAG

# Alpine Package Pipeline
build-alpine:
  stage: build
  image: alpine:3.19
  script:
    - apk add --no-cache alpine-sdk sudo
    - adduser -D builder && addgroup builder abuild
    - echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
    - su builder -c "abuild-keygen -an"
    - su builder -c "abuild -r"
  artifacts:
    paths:
      - "packages/**/*.apk"
    expire_in: 1 hour
  rules:
    - if: $CI_COMMIT_TAG

publish-alpine:
  stage: publish
  image: curlimages/curl:latest
  needs: [build-alpine]
  script:
    - |
      find packages -name "*.apk" -exec curl -X POST \
        -H "X-API-Key: ${PACKAGE_REPO_API_KEY}" \
        -F "file=@{}" \
        "${REPO_URL}/api/v1/upload/alpine" \;
  rules:
    - if: $CI_COMMIT_TAG
